// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { DurableObjectNamespace, Rpc } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		COUNTER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.counter').Counter>
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
