// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { DurableObjectNamespace, Rpc } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		COUNTER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.counter').Counter>
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		COUNTER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.counter').Counter>
	}
}

export {}
