// =============================================================================
// CLI type-generation — generateBindingTypes fixture (P1-codegen)
// =============================================================================
//
// Pins the public shape of the generated `env.d.ts` source: a global
// `interface DevflareEnv` containing one typed member per binding from the
// resolved devflare config. This is the contract relied on by:
//   - src/env.ts                  (declares `interface DevflareEnv {}`)
//   - src/test/simple-context.ts  (consumes DevflareEnv in test contexts)
//   - src/runtime/exports.ts      (re-exports DevflareEnv to user code)
//
// Keeping the shape covered by a fixture-based test avoids silent regressions
// when the generator's binding-walker changes.
// =============================================================================

import { describe, expect, test } from 'bun:test'
import { generateBindingTypes } from '../../../../src/cli/commands/type-generation/generator'

const fixtureConfig = {
	bindings: {
		kv: { MY_KV: { id: 'kv-id', preview_id: 'kv-prev' } },
		d1: { MY_DB: { database_id: 'db-1', database_name: 'db' } },
		r2: { MY_BUCKET: 'bucket-1' },
		queues: { producers: { MY_QUEUE: 'queue-1' } },
		ai: { binding: 'AI' },
		browser: { MY_BROWSER: 'browser-1' }
	},
	vars: { MY_VAR: 'hello' },
	secrets: { MY_SECRET: { required: true } }
}

describe('generateBindingTypes — P1-codegen fixture', () => {
	const generated = generateBindingTypes(fixtureConfig, [], [], [], '/tmp/fake-project')

	test('emits the canonical "DO NOT EDIT" header', () => {
		expect(generated.startsWith('// Generated by devflare - DO NOT EDIT')).toBe(true)
	})

	test('imports the workers-types it actually uses', () => {
		expect(generated).toContain("import type {")
		expect(generated).toContain("from '@cloudflare/workers-types'")
		expect(generated).toContain('KVNamespace')
		expect(generated).toContain('D1Database')
		expect(generated).toContain('R2Bucket')
		expect(generated).toContain('Queue')
		expect(generated).toContain('Ai')
		expect(generated).toContain('Fetcher')
	})

	test('declares the DevflareEnv interface with one member per binding', () => {
		expect(generated).toContain('declare global {')
		expect(generated).toContain('interface DevflareEnv {')
		expect(generated).toContain('MY_KV: KVNamespace')
		expect(generated).toContain('MY_DB: D1Database')
		expect(generated).toContain('MY_BUCKET: R2Bucket')
		expect(generated).toContain('MY_QUEUE: Queue')
		expect(generated).toContain('MY_BROWSER: Fetcher')
		expect(generated).toContain('MY_VAR: string')
		expect(generated).toContain('MY_SECRET: string')
	})

	test('emits the Entrypoints type fallback when no entrypoints were discovered', () => {
		expect(generated).toContain('export type Entrypoints = string')
	})

	test('emits a typed Entrypoints union when entrypoints are discovered', () => {
		const withEntrypoints = generateBindingTypes(
			fixtureConfig,
			[],
			[
				{ className: 'WorkerA', filePath: '/tmp/fake-project/src/ep.workerA.ts' },
				{ className: 'WorkerB', filePath: '/tmp/fake-project/src/ep.workerB.ts' }
			],
			[],
			'/tmp/fake-project'
		)
		expect(withEntrypoints).toContain("export type Entrypoints = 'WorkerA' | 'WorkerB'")
	})

	test('empty config still emits a valid empty DevflareEnv block', () => {
		const empty = generateBindingTypes({}, [], [], [], '/tmp/fake-project')
		expect(empty).toContain('declare global {')
		expect(empty).toContain('interface DevflareEnv {')
		expect(empty).toContain('export type Entrypoints = string')
	})
})
