// =============================================================================
// CLI type-generation — generateBindingTypes fixture (P1-codegen)
// =============================================================================
//
// Pins the public shape of the generated `env.d.ts` source: a global
// `interface DevflareEnv` containing one typed member per binding from the
// resolved devflare config, plus typed config vars inferred from the user's
// config. This is the contract relied on by:
//   - src/env.ts                  (declares `interface DevflareEnv {}`)
//   - src/test/simple-context.ts  (consumes DevflareEnv in test contexts)
//   - src/runtime/exports.ts      (re-exports DevflareEnv to user code)
//
// Keeping the shape covered by a fixture-based test avoids silent regressions
// when the generator's binding-walker changes.
// =============================================================================

import { describe, expect, test } from 'bun:test'
import { generateBindingTypes } from '../../../../src/cli/commands/type-generation/generator'

const fixtureConfig = {
	bindings: {
		kv: { MY_KV: { id: 'kv-id', preview_id: 'kv-prev' } },
		d1: { MY_DB: { id: 'db-1' } },
		r2: { MY_BUCKET: 'bucket-1' },
		queues: { producers: { MY_QUEUE: 'queue-1' } },
		rateLimits: {
			MY_RATE_LIMITER: {
				namespaceId: '1001',
				simple: { limit: 100, period: 60 as const }
			}
		},
		versionMetadata: { binding: 'CF_VERSION_METADATA' },
		workerLoaders: {
			LOADER: {}
		},
		mtlsCertificates: {
			API_CERT: {
				certificateId: 'cert-123'
			}
		},
		dispatchNamespaces: {
			DISPATCHER: {
				namespace: 'customers'
			}
		},
		workflows: {
			ORDER_WORKFLOW: {
				name: 'orders',
				className: 'OrderWorkflow'
			}
		},
		pipelines: {
			EVENTS: {
				pipeline: 'events-stream'
			}
		},
		images: {
			IMAGES: {
				remote: true
			}
		},
		media: {
			MEDIA: {
				remote: true
			}
		},
		artifacts: {
			ARTIFACTS: {
				namespace: 'default'
			}
		},
		secretsStore: {
			API_TOKEN: {
				storeId: 'store-123',
				secretName: 'api-token'
			}
		},
		ai: {
			binding: 'AI',
			remote: true,
			staging: true
		},
		aiSearchNamespaces: {
			AI_SEARCH: {
				namespace: 'default',
				remote: true
			}
		},
		aiSearch: {
			DOCS_SEARCH: {
				instanceName: 'docs',
				remote: true
			}
		},
		browser: {
			MY_BROWSER: {
				remote: true
			}
		}
	},
	rules: [
		{ type: 'Text', globs: ['**/*.txt'] },
		{ type: 'Data', globs: ['**/*.bin'] },
		{ type: 'CompiledWasm', globs: ['**/*.wasm'] },
		{ type: 'ESModule', globs: ['**/*.mjs'] }
	],
	vars: { MY_VAR: 'hello' },
	secrets: { MY_SECRET: { required: true } }
}

describe('generateBindingTypes — P1-codegen fixture', () => {
	const generated = generateBindingTypes(fixtureConfig, [], [], [], '/tmp/fake-project')

	test('emits the canonical "DO NOT EDIT" header', () => {
		expect(generated.startsWith('// Generated by devflare - DO NOT EDIT')).toBe(true)
	})

	test('imports the workers-types it actually uses', () => {
		expect(generated).toContain("import type {")
		expect(generated).toContain("from '@cloudflare/workers-types'")
		expect(generated).toContain("import type { Pipeline } from 'cloudflare:pipelines'")
		expect(generated).toContain('KVNamespace')
		expect(generated).toContain('D1Database')
		expect(generated).toContain('R2Bucket')
		expect(generated).toContain('Queue')
		expect(generated).toContain('RateLimit')
		expect(generated).toContain('WorkerVersionMetadata')
		expect(generated).toContain('WorkerLoader')
		expect(generated).toContain('DispatchNamespace')
		expect(generated).toContain('Workflow')
		expect(generated).toContain('ImagesBinding')
		expect(generated).toContain('MediaBinding')
		expect(generated).toContain('Artifacts')
		expect(generated).toContain('SecretsStoreSecret')
		expect(generated).toContain('Ai')
		expect(generated).toContain('AiSearchNamespace')
		expect(generated).toContain('AiSearchInstance')
		expect(generated).toContain('Fetcher')
	})

	test('declares the DevflareEnv interface with one member per binding', () => {
		expect(generated).toContain('declare global {')
		expect(generated).toContain("import type { InferConfigVars } from 'devflare/config'")
		expect(generated).toContain(
			"type __DevflareConfigVars = InferConfigVars<Awaited<typeof import('./devflare.config').default>>"
		)
		expect(generated).toContain('interface DevflareVars extends __DevflareConfigVars {}')
		expect(generated).toContain('interface DevflareEnv extends __DevflareConfigVars {')
		expect(generated).toContain('MY_KV: KVNamespace')
		expect(generated).toContain('MY_DB: D1Database')
		expect(generated).toContain('MY_BUCKET: R2Bucket')
		expect(generated).toContain('MY_QUEUE: Queue')
		expect(generated).toContain('MY_RATE_LIMITER: RateLimit')
		expect(generated).toContain('CF_VERSION_METADATA: WorkerVersionMetadata')
		expect(generated).toContain('LOADER: WorkerLoader')
		expect(generated).toContain('API_CERT: Fetcher')
		expect(generated).toContain('DISPATCHER: DispatchNamespace')
		expect(generated).toContain('ORDER_WORKFLOW: Workflow')
		expect(generated).toContain('EVENTS: Pipeline')
		expect(generated).toContain('IMAGES: ImagesBinding')
		expect(generated).toContain('MEDIA: MediaBinding')
		expect(generated).toContain('ARTIFACTS: Artifacts')
		expect(generated).toContain('API_TOKEN: SecretsStoreSecret')
		expect(generated).toContain('AI_SEARCH: AiSearchNamespace')
		expect(generated).toContain('DOCS_SEARCH: AiSearchInstance')
		expect(generated).toContain('MY_BROWSER: Fetcher')
		expect(generated).toContain('MY_SECRET: string')
	})

	test('emits ambient module declarations for native module rules', () => {
		expect(generated).toContain("declare module '*.txt'")
		expect(generated).toContain('const value: string')
		expect(generated).toContain("declare module '*.bin'")
		expect(generated).toContain('const value: ArrayBuffer')
		expect(generated).toContain("declare module '*.wasm'")
		expect(generated).toContain('const value: WebAssembly.Module')
		expect(generated).not.toContain("declare module '*.mjs'")
	})

	test('emits the Entrypoints type fallback when no entrypoints were discovered', () => {
		expect(generated).toContain('export type Entrypoints = string')
	})

	test('emits a typed Entrypoints union when entrypoints are discovered', () => {
		const withEntrypoints = generateBindingTypes(
			fixtureConfig,
			[],
			[
				{ className: 'WorkerA', filePath: '/tmp/fake-project/src/ep.workerA.ts' },
				{ className: 'WorkerB', filePath: '/tmp/fake-project/src/ep.workerB.ts' }
			],
			[],
			'/tmp/fake-project'
		)
		expect(withEntrypoints).toContain("export type Entrypoints = 'WorkerA' | 'WorkerB'")
	})

	test('empty config still emits a valid empty DevflareEnv block', () => {
		const empty = generateBindingTypes({}, [], [], [], '/tmp/fake-project')
		expect(empty).toContain('declare global {')
		expect(empty).toContain('interface DevflareEnv {')
		expect(empty).toContain('export type Entrypoints = string')
	})
})
