// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		CACHE: KVNamespace
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		CACHE: KVNamespace
	}
}

export {}
