// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace, Queue } from '@cloudflare/workers-types'
import type { Task } from './src/lib/types'

declare global {
	interface DevflareEnv {
		RESULTS: KVNamespace
		TASK_QUEUE: Queue<Task>
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		RESULTS: KVNamespace
		TASK_QUEUE: Queue<Task>
	}
}

export {}
