// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace, SendEmail } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		EMAIL_LOG: KVNamespace
		EMAIL: SendEmail
		FORWARD_ADDRESS: string
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
