// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace, SendEmail } from '@cloudflare/workers-types'

import type { InferConfigVars } from 'devflare/config'
type __DevflareConfigVars = InferConfigVars<Awaited<typeof import('./devflare.config').default>>

declare global {
	interface DevflareVars extends __DevflareConfigVars {}
	interface DevflareEnv extends __DevflareConfigVars {
		EMAIL_LOG: KVNamespace
		EMAIL: SendEmail
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
