// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace, SendEmail } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		EMAIL_LOG: KVNamespace
		EMAIL: SendEmail
		FORWARD_ADDRESS: string
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		EMAIL_LOG: KVNamespace
		EMAIL: SendEmail
		FORWARD_ADDRESS: string
	}
}

export { }
