// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { Ai, KVNamespace, VectorizeIndex } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		CACHE: KVNamespace
		AI: Ai
		VECTORIZE: VectorizeIndex
		EMBEDDING_MODEL: string
		TEXT_MODEL: string
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
