// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { Ai, VectorizeIndex, KVNamespace } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		AI: Ai
		VECTORIZE: VectorizeIndex
		CACHE: KVNamespace
		EMBEDDING_MODEL: string
		TEXT_MODEL: string
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		AI: Ai
		VECTORIZE: VectorizeIndex
		CACHE: KVNamespace
		EMBEDDING_MODEL: string
		TEXT_MODEL: string
	}
}

export {}
