// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		WORKFLOW_STATE: KVNamespace
		RESULTS: KVNamespace
		MAX_RETRIES: string
		RETRY_DELAY_MS: string
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
