// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		WORKFLOW_STATE: KVNamespace
		RESULTS: KVNamespace
		MAX_RETRIES: string
		RETRY_DELAY_MS: string
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		WORKFLOW_STATE: KVNamespace
		RESULTS: KVNamespace
		MAX_RETRIES: string
		RETRY_DELAY_MS: string
	}
}

export {}
