import { basename, isAbsolute, relative, resolve } from 'pathe'
import { generatedDir } from '../../utils/generated-dir'
import type { WranglerConfig } from './types'

/**
 * Convert WranglerConfig to JSONC string with comments
 */
export function stringifyConfig(config: WranglerConfig): string {
	const header = `// Generated by devflare — Do not edit directly
// Edit devflare.config.ts instead

`
	return header + JSON.stringify(config, null, '\t')
}

function rebasePathForConfigDir(projectRoot: string, configDir: string, pathValue: string): string {
	const absolutePath = isAbsolute(pathValue) ? pathValue : resolve(projectRoot, pathValue)

	return relative(configDir, absolutePath).replace(/\\/g, '/')
}

function isLocalContainerPath(pathValue: string): boolean {
	return (
		pathValue === 'Dockerfile' ||
		pathValue.startsWith('.') ||
		pathValue.startsWith('/') ||
		pathValue.startsWith('\\') ||
		isAbsolute(pathValue) ||
		pathValue.endsWith('/Dockerfile') ||
		pathValue.endsWith('\\Dockerfile')
	)
}

function pathIsInsideDirectory(directoryPath: string, candidatePath: string): boolean {
	const normalizedDirectoryPath = directoryPath.replace(/\\/g, '/')
	const normalizedCandidatePath = candidatePath.replace(/\\/g, '/')

	return (
		normalizedCandidatePath === normalizedDirectoryPath ||
		normalizedCandidatePath.startsWith(`${normalizedDirectoryPath}/`)
	)
}

export function isolateViteBuildOutputPaths(
	projectRoot: string,
	config: WranglerConfig
): WranglerConfig {
	const assetsDirectory = config.assets?.directory
	if (!assetsDirectory) {
		return config
	}

	const isolatedAssetsDirectoryPath = generatedDir(
		projectRoot,
		'vite-build-output',
		basename(assetsDirectory)
	)
	const isolatedAssetsDirectory = relative(projectRoot, isolatedAssetsDirectoryPath).replace(
		/\\/g,
		'/'
	)
	const isolatedConfig: WranglerConfig = {
		...config,
		assets: config.assets
			? {
					...config.assets,
					directory: isolatedAssetsDirectory
				}
			: config.assets
	}

	if (!config.main) {
		return isolatedConfig
	}

	const originalAssetsDirectoryPath = resolve(projectRoot, assetsDirectory)
	const originalMainEntryPath = resolve(projectRoot, config.main)
	if (!pathIsInsideDirectory(originalAssetsDirectoryPath, originalMainEntryPath)) {
		return isolatedConfig
	}

	const relativeMainEntryPath = relative(originalAssetsDirectoryPath, originalMainEntryPath)
	const isolatedMainEntryPath = resolve(isolatedAssetsDirectoryPath, relativeMainEntryPath)

	return {
		...isolatedConfig,
		main: relative(projectRoot, isolatedMainEntryPath).replace(/\\/g, '/')
	}
}

export function rebaseWranglerConfigPaths(
	projectRoot: string,
	configDir: string,
	config: WranglerConfig
): WranglerConfig {
	return {
		...config,
		...(config.main ? { main: rebasePathForConfigDir(projectRoot, configDir, config.main) } : {}),
		...(config.assets?.directory
			? {
					assets: {
						...config.assets,
						directory: rebasePathForConfigDir(projectRoot, configDir, config.assets.directory)
					}
				}
			: {}),
		...(config.containers
			? {
					containers: config.containers.map((container) => ({
						...container,
						image: isLocalContainerPath(container.image)
							? rebasePathForConfigDir(projectRoot, configDir, container.image)
							: container.image,
						...(container.image_build_context && {
							image_build_context: rebasePathForConfigDir(
								projectRoot,
								configDir,
								container.image_build_context
							)
						})
					}))
				}
			: {})
	}
}

/**
 * Write wrangler.jsonc file to the specified directory
 *
 * @param cwd - Working directory to write to
 * @param config - Wrangler configuration to write
 * @param filename - Optional filename (default: 'wrangler.jsonc')
 * @returns Path to the written file
 */
export async function writeWranglerConfig(
	cwd: string,
	config: WranglerConfig,
	filename = 'wrangler.jsonc'
): Promise<string> {
	const { resolve } = await import('pathe')
	const fs = await import('node:fs/promises')

	// Ensure directory exists
	try {
		await fs.mkdir(cwd, { recursive: true })
	} catch {
		// Directory may already exist
	}

	const content = stringifyConfig(config)
	const wranglerPath = resolve(cwd, filename)
	await fs.writeFile(wranglerPath, content, 'utf-8')
	return wranglerPath
}

export async function readWranglerConfig(filePath: string): Promise<WranglerConfig> {
	const fs = await import('node:fs/promises')
	const { parse } = await import('jsonc-parser')
	const content = await fs.readFile(filePath, 'utf-8')
	const parsedConfig = parse(content)

	if (!parsedConfig || typeof parsedConfig !== 'object') {
		throw new Error(`Could not parse Wrangler config at ${filePath}.`)
	}

	return parsedConfig as WranglerConfig
}
