// =============================================================================
// Case 18: SvelteKit App Type Definitions
// =============================================================================

// DevflareEnv is globally declared by env.d.ts (generated by `devflare types`)

declare global {
	namespace App {
		interface Platform {
			env: DevflareEnv
			context: {
				waitUntil(promise: Promise<unknown>): void
			}
		}

		interface Locals {
			// Add any request-local data here
		}

		interface PageData {
			// Add any shared page data here
		}

		interface Error {
			message: string
			code?: string
		}
	}
}

export { }
