// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

declare global {
	interface DevflareEnv {
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
	}
}

/**
 * Named entrypoints discovered from ep.*.ts files.
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = 'AdminEntrypoint'

export { }
