// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { DurableObjectNamespace, Rpc } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		COUNTER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./do.counter').Counter>
		RATE_LIMITER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./do.rate-limiter').RateLimiter>
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		COUNTER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./do.counter').Counter>
		RATE_LIMITER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./do.rate-limiter').RateLimiter>
	}
}

export { }
