// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { DurableObjectNamespace, Rpc } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		SESSION_STORE: DurableObjectNamespace<Rpc.DurableObjectBranded & import('../case11-do-shared/src/do.session').SessionStore>
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		SESSION_STORE: DurableObjectNamespace<Rpc.DurableObjectBranded & import('../case11-do-shared/src/do.session').SessionStore>
	}
}

export {}
