// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type {
	D1Database,
	DurableObjectNamespace,
	Fetcher,
	Hyperdrive,
	ImagesBinding,
	KVNamespace,
	MediaBinding,
	R2Bucket,
	Rpc,
	SecretsStoreSecret,
	SendEmail,
	WorkerLoader,
	Workflow
} from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		CACHE: KVNamespace
		DB: D1Database
		IMAGES: R2Bucket
		CHAT_ROOM: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.chat-room').ChatRoom>
		PDF_RENDERER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.pdf-renderer').PdfRenderer>
		BROWSER: Fetcher
		POSTGRES: Hyperdrive
		WORKER_LOADER: WorkerLoader
		ORDER_WORKFLOW: Workflow<{ orderId: string; total: number }>
		IMAGES_SERVICE: ImagesBinding
		MEDIA_SERVICE: MediaBinding
		API_TOKEN: SecretsStoreSecret
		EMAIL: SendEmail
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		CACHE: KVNamespace
		DB: D1Database
		IMAGES: R2Bucket
		CHAT_ROOM: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.chat-room').ChatRoom>
		PDF_RENDERER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.pdf-renderer').PdfRenderer>
		BROWSER: Fetcher
		POSTGRES: Hyperdrive
		WORKER_LOADER: WorkerLoader
		ORDER_WORKFLOW: Workflow<{ orderId: string; total: number }>
		IMAGES_SERVICE: ImagesBinding
		MEDIA_SERVICE: MediaBinding
		API_TOKEN: SecretsStoreSecret
		EMAIL: SendEmail
	}
}

export {}
