// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { D1Database, DurableObjectNamespace, Fetcher, KVNamespace, R2Bucket, Rpc } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		CACHE: KVNamespace
		DB: D1Database
		IMAGES: R2Bucket
		CHAT_ROOM: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.chat-room').ChatRoom>
		PDF_RENDERER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.pdf-renderer').PdfRenderer>
		BROWSER: Fetcher
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		CACHE: KVNamespace
		DB: D1Database
		IMAGES: R2Bucket
		CHAT_ROOM: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.chat-room').ChatRoom>
		PDF_RENDERER: DurableObjectNamespace<Rpc.DurableObjectBranded & import('./src/do.pdf-renderer').PdfRenderer>
		BROWSER: Fetcher
	}
}

export {}
