import adapter from '@sveltejs/adapter-cloudflare'
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte'

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: vitePreprocess(),
	kit: {
		adapter: adapter({
			// Use config from .devflare/ (generated by devflare plugin)
			config: '.devflare/wrangler.jsonc',
			platformProxy: {
				// Use the generated config for getPlatformProxy
				configPath: '.devflare/wrangler.jsonc',
				persist: true
			}
		}),
		alias: {
			$lib: './src/lib'
		}
	}
}

export default config
