// =============================================================================
// Case 18: Vite Configuration with Durable Object Support
// =============================================================================
// This configuration sets up SvelteKit with Cloudflare adapter.
//
// For Durable Objects to work locally:
// - Run `devflare dev` which starts wrangler with multi-config support
// - Main worker: wrangler.jsonc (SvelteKit app with service binding to DO worker)
// - DO worker: wrangler.do.jsonc (exports ChatRoom, PdfRenderer classes)
// - SvelteKit calls DOs via DO_SERVICE service binding
//
// The wrangler.jsonc files are generated by devflare dev.
// =============================================================================

import { sveltekit } from '@sveltejs/kit/vite'
import { devflarePlugin } from 'devflare/vite'
import { defineConfig } from 'vite'

export default defineConfig({
	plugins: [
		// Devflare plugin (loads config, generates wrangler.jsonc for platformProxy)
		// WebSocket routes are configured in devflare.config.ts wsRoutes
		devflarePlugin(),

		// SvelteKit (handles the main app with adapter-cloudflare)
		sveltekit()
	],

	// Resolve aliases for imports
	resolve: {
		alias: {
			$lib: './src/lib'
		}
	}
})

