// =============================================================================
// Devflare Vite plugin — Durable Object discovery + auxiliary worker helpers
// =============================================================================
// Pure helpers extracted from `vite/plugin.ts`:
//  - DO file/class discovery (re-exported from shared
//    `worker-entry/durable-object-discovery.ts`)
//  - Virtual DO entry module codegen (`generateVirtualDOEntry`)
//  - Auxiliary worker config construction (`createAuxiliaryWorkerConfig`)
//  - Diagnostic logging (`logDiscoveredDurableObjects`)
//
// `VIRTUAL_DO_ENTRY` is duplicated here so the helpers stay self-contained;
// `plugin.ts` re-exports the same constant for backwards compatibility.
// =============================================================================

import type { WranglerConfig } from '../config/compiler'
import {
	type DODiscoveryResult,
	discoverDurableObjects
} from '../worker-entry/durable-object-discovery'

export const VIRTUAL_DO_ENTRY = 'virtual:devflare-do-entry'
export const RESOLVED_VIRTUAL_DO_ENTRY = '\0' + VIRTUAL_DO_ENTRY

// Re-exported from the shared helper so existing import paths keep working.
export { discoverDurableObjects, type DODiscoveryResult }

export interface AuxiliaryWorkerConfig {
	config: Record<string, unknown>
}

/**
 * Generate virtual DO entry module code
 */
export function generateVirtualDOEntry(discovery: DODiscoveryResult): string {
	const lines: string[] = [
		'// Auto-generated by devflare — DO entry module',
		'// Re-exports all Durable Object classes discovered from files.durableObjects pattern',
		''
	]

	for (const [filePath, classNames] of discovery.files) {
		const normalizedPath = filePath.replace(/\\/g, '/')
		lines.push(`export { ${classNames.join(', ')} } from '${normalizedPath}'`)
	}

	lines.push('')
	lines.push('// Default fetch handler for DO worker')
	lines.push('export default {')
	lines.push('\tasync fetch(request: Request): Promise<Response> {')
	lines.push('\t\treturn new Response("Devflare DO Worker", { status: 200 })')
	lines.push('\t}')
	lines.push('}')

	return lines.join('\n')
}

/**
 * Create auxiliary worker config for Durable Objects
 */
export function createAuxiliaryWorkerConfig(
	wranglerConfig: WranglerConfig,
	discovery: DODiscoveryResult
): AuxiliaryWorkerConfig {
	const doBindings =
		wranglerConfig.durable_objects?.bindings?.map((binding) => ({
			name: binding.name,
			class_name: binding.class_name
		})) ?? []

	return {
		config: {
			name: discovery.workerName,
			main: VIRTUAL_DO_ENTRY,
			compatibility_date: wranglerConfig.compatibility_date,
			compatibility_flags: wranglerConfig.compatibility_flags,
			durable_objects: { bindings: doBindings },
			migrations: wranglerConfig.migrations,
			kv_namespaces: wranglerConfig.kv_namespaces,
			d1_databases: wranglerConfig.d1_databases,
			r2_buckets: wranglerConfig.r2_buckets,
			browser: wranglerConfig.browser
		}
	}
}

export function logDiscoveredDurableObjects(
	projectRoot: string,
	discovery: DODiscoveryResult | null
): void {
	if (!discovery || discovery.files.size === 0) {
		return
	}

	console.log(`[devflare] Discovered ${discovery.files.size} DO file(s):`)
	for (const [filePath, classes] of discovery.files) {
		console.log(`  • ${filePath.replace(projectRoot, '.')} → ${classes.join(', ')}`)
	}
}
