// =============================================================================
// Case 20: SvelteKit 3 App Type Definitions
// =============================================================================
// DevflareEnv is declared globally by env.d.ts (generated by `devflare types`).
// SvelteKit 3 apps read their bindings from `cloudflare:workers`, whose `env`
// is typed as `Cloudflare.Env`, so that interface takes DevflareEnv's members.

declare global {
	namespace Cloudflare {
		interface Env extends DevflareEnv {}
	}
}

export {}
