// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

declare global {
	interface DevflareEnv {
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
