// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

declare global {
	interface DevflareEnv {
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
	}
}

export {}
