// =============================================================================
// Case 5: Multi-Worker (RPC) - Gateway Tests using devflare test context
// =============================================================================
// This test demonstrates devflare's standard test pattern for multi-worker RPC.
//
// Pattern:
// - Use createTestContext() which auto-detects service bindings from config
// - Access service bindings via env.MATH_SERVICE (default) and env.ADMIN (named)
// - The math-service worker.ts is automatically bundled and transformed
// - Run `devflare types` to generate typed service bindings in env.d.ts
//
// Naming Conventions:
//   worker.ts    — Default worker export (transformed to WorkerEntrypoint)
//   ep.*.ts      — Named entrypoints (classes extending WorkerEntrypoint)
//   do.*.ts      — Durable Objects (classes extending DurableObject)
//   wf.*.ts      — Workflows (classes extending Workflow)
// =============================================================================

import { describe, test, expect, beforeAll, afterAll } from 'bun:test'
import { createTestContext } from 'devflare/test'
import { env } from 'devflare'

// Types are generated by `devflare types` in env.d.ts
// The generated types include:
//   MATH_SERVICE: MathServiceInterface
//   ADMIN: AdminEntrypointInterface

// -----------------------------------------------------------------------------
// Test Setup
// -----------------------------------------------------------------------------

beforeAll(async () => {
	await createTestContext()
})

afterAll(async () => {
	await env.dispose()
})

// -----------------------------------------------------------------------------
// Tests
// -----------------------------------------------------------------------------

describe('Case 5: Multi-Worker RPC via WorkerEntrypoint', () => {
	// -------------------------------------------------------------------------
	// Default Worker Tests (worker.ts → MATH_SERVICE binding)
	// -------------------------------------------------------------------------
	describe('Default worker.ts binding (MATH_SERVICE)', () => {
		test('add() returns sum of two numbers', async () => {
			const result = await env.MATH_SERVICE.add(5, 3)
			expect(result).toBe(8)
		})

		test('add() handles negative numbers', async () => {
			const result = await env.MATH_SERVICE.add(-10, 4)
			expect(result).toBe(-6)
		})

		test('add() handles decimals', async () => {
			const result = await env.MATH_SERVICE.add(1.5, 2.5)
			expect(result).toBe(4)
		})

		test('multiply() returns product of two numbers', async () => {
			const result = await env.MATH_SERVICE.multiply(6, 7)
			expect(result).toBe(42)
		})

		test('multiply() handles zero', async () => {
			const result = await env.MATH_SERVICE.multiply(100, 0)
			expect(result).toBe(0)
		})

		test('fibonacci() calculates correct value', async () => {
			const result = await env.MATH_SERVICE.fibonacci(10)
			expect(result).toBe(55) // fib(10) = 55
		})

		test('fibonacci() handles base cases', async () => {
			expect(await env.MATH_SERVICE.fibonacci(0)).toBe(0)
			expect(await env.MATH_SERVICE.fibonacci(1)).toBe(1)
		})

		test('calculateStats() returns correct statistics', async () => {
			const stats = await env.MATH_SERVICE.calculateStats([1, 2, 3, 4, 5])
			expect(stats.count).toBe(5)
			expect(stats.sum).toBe(15)
			expect(stats.mean).toBe(3)
			expect(stats.min).toBe(1)
			expect(stats.max).toBe(5)
		})

		test('calculateStats() handles empty array', async () => {
			const stats = await env.MATH_SERVICE.calculateStats([])
			expect(stats.count).toBe(0)
			expect(stats.sum).toBe(0)
		})

		test('calculateStats() handles single number', async () => {
			const stats = await env.MATH_SERVICE.calculateStats([42])
			expect(stats.count).toBe(1)
			expect(stats.sum).toBe(42)
			expect(stats.mean).toBe(42)
			expect(stats.min).toBe(42)
			expect(stats.max).toBe(42)
		})
	})

	// -------------------------------------------------------------------------
	// Named Entrypoint Tests (ep.admin.ts → ADMIN binding)
	// -------------------------------------------------------------------------
	describe('Named entrypoint binding (ADMIN)', () => {
		test('resetStats() returns success', async () => {
			const result = await env.ADMIN.resetStats()
			expect(result.success).toBe(true)
			expect(typeof result.timestamp).toBe('number')
		})

		test('getHealth() returns health status', async () => {
			const health = await env.ADMIN.getHealth()
			expect(health.status).toBe('healthy')
			expect(typeof health.uptime).toBe('number')
			expect(health.version).toBe('1.0.0')
		})

		test('runDiagnostics() returns metrics', async () => {
			const diagnostics = await env.ADMIN.runDiagnostics()
			expect(typeof diagnostics.memoryUsage).toBe('number')
			expect(typeof diagnostics.cpuUsage).toBe('number')
			expect(typeof diagnostics.requestCount).toBe('number')
		})
	})
})
