// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { KVNamespace } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		LOG_STORE: KVNamespace
		MIN_LOG_LEVEL: string
	}
}

/**
 * Named entrypoints (none discovered - add ep.*.ts files to enable).
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = string
