// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { AdminEntrypointInterface, MathServiceInterface } from './src/math-service.types'

declare global {
	interface DevflareEnv {
		MATH_SERVICE: MathServiceInterface
		ADMIN: AdminEntrypointInterface
	}
}

/**
 * Named entrypoints discovered from ep.*.ts files.
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = 'AdminEntrypoint'
