// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type {
	Fetcher,
	Hyperdrive,
	ImagesBinding,
	MediaBinding,
	SecretsStoreSecret,
	SendEmail,
	WorkerLoader,
	Workflow
} from '@cloudflare/workers-types'

import type { InferConfigVars } from 'devflare/config'

type __DevflareConfigVars = InferConfigVars<Awaited<typeof import('./devflare.config').default>>

declare global {
	interface DevflareVars extends __DevflareConfigVars {}
	interface DevflareEnv extends __DevflareConfigVars {
		WORKER_LOADER: WorkerLoader
		ORDER_WORKFLOW: Workflow
		IMAGES_SERVICE: ImagesBinding
		MEDIA_SERVICE: MediaBinding
		API_TOKEN: SecretsStoreSecret
		CASE20_API: Fetcher
		POSTGRES: Hyperdrive
		EMAIL: SendEmail
	}
}

/**
 * Named entrypoints discovered from ep.*.ts files.
 * Use with defineConfig<Entrypoints>() for type-safe cross-worker references.
 */
export type Entrypoints = 'Case20Api'
