// Generated by devflare - DO NOT EDIT
// Run `devflare types` to regenerate

import type { Hyperdrive } from '@cloudflare/workers-types'

declare global {
	interface DevflareEnv {
		DB: Hyperdrive
	}
}

declare module 'devflare/test' {
	interface DevflareEnv {
		DB: Hyperdrive
	}
}

export {}
